apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      persistentVolumeClaim:
        claimName: my-pvc
